# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrMhkRPDy7BehlbDzY2P6P95zsz5dSrs
"""

# ===============================
# MODEL – Kelompok 11 (RF + XGBoost)
# ===============================

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from xgboost import XGBClassifier

# ------------------------
# 1. LOAD DATA
# ------------------------
df = pd.read_csv("obesity_level.csv")

# ------------------------
# 2. DATA CLEANING (sesuai PDF)
# ------------------------
df = df.rename(columns={'0be1dad': 'Obesity Level'})

df['CALC'] = df['CALC'].astype(str).replace('0', 'Never')
df['CAEC'] = df['CAEC'].astype(str).replace('0', 'Never')

df.drop(columns=['id'], inplace=True)

df['Obesity Level'] = df['Obesity Level'].replace({
    '0rmal_Weight': 'Normal_Weight'
})

# ------------------------
# 3. OUTLIER HANDLING (IQR + Capping)
# ------------------------
num_cols = ['Age','Height','Weight','FCVC','NCP','CH2O','FAF','TUE']

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR
    df[col] = df[col].clip(lower, upper)

# ------------------------
# 4. MANUAL ENCODING (sesuai PDF)
# ------------------------
gender_map = {'Male': 1, 'Female': 0}
caec_map   = {'Sometimes':1, 'Frequently':2, 'Always':3, 'Never':0}
calc_map   = {'Sometimes':1, 'Frequently':2, 'Never':0}
mtrans_map = {
    'Public_Transportation': 0,
    'Automobile': 1,
    'Walking': 2,
    'Bike': 3,
    'Motorbike': 4
}
obesity_map = {
    'Insufficient_Weight': 0,
    'Normal_Weight': 1,
    'Overweight_Level_I': 2,
    'Overweight_Level_II': 3,
    'Obesity_Type_I': 4,
    'Obesity_Type_II': 5,
    'Obesity_Type_III': 6
}

df['Gender'] = df['Gender'].map(gender_map)
df['CAEC'] = df['CAEC'].map(caec_map)
df['CALC'] = df['CALC'].map(calc_map)
df['MTRANS'] = df['MTRANS'].map(mtrans_map)
df['Obesity Level'] = df['Obesity Level'].map(obesity_map)

# ------------------------
# 5. FEATURE ENGINEERING: Binning
# ------------------------
age_bins = [10, 20, 30, 40, 50, 65]
age_labels = ['10-20','21-30','31-40','41-50','51-65']
df['Age_Group'] = pd.cut(df['Age'], bins=age_bins, labels=age_labels, right=False)

weight_bins = [30,60,80,100,120,140,180]
weight_labels = ['30-60','60-80','80-100','100-120','120-140','>140']
df['Weight_Group'] = pd.cut(df['Weight'], bins=weight_bins, labels=weight_labels, right=False)

# Encoding kategori hasil binning
le = LabelEncoder()
df['Age_Group'] = le.fit_transform(df['Age_Group'])
df['Weight_Group'] = le.fit_transform(df['Weight_Group'])

# ------------------------
# 6. SPLIT DATA
# ------------------------
X = df.drop(columns=['Obesity Level'])
y = df['Obesity Level']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ------------------------
# 7. SCALING
# ------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ------------------------
# 8. MODEL 1 – RANDOM FOREST (tuned)
# ------------------------
rf_model = RandomForestClassifier(
    n_estimators=300,
    min_samples_split=5,
    min_samples_leaf=1,
    max_features='log2',
    max_depth=15,
    bootstrap=True,
    random_state=42
)
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)
print("RandomForest Accuracy:", accuracy_score(y_test, rf_pred))

# ------------------------
# 9. MODEL 2 – XGBOOST
# ------------------------
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.1,
    objective='multi:softmax',
    num_class=7,
    eval_metric='mlogloss'
)
xgb.fit(X_train_scaled, y_train)

xgb_pred = xgb.predict(X_test_scaled)
print("XGBoost Accuracy:", accuracy_score(y_test, xgb_pred))

# ------------------------
# 10. SAVE MODEL
# ------------------------
joblib.dump(rf_model, "kel11_rf_model.sav")
joblib.dump(xgb, "kel11_xgb_model.sav")
joblib.dump(scaler, "kel11_scaler.sav")

print("All models saved successfully!")